var origBoard = [];

//Assuming player 1 chhoses 0
const player1 = 'O';
const player2 = 'X';

//winning combination will be generated by function
//const wincombos;

//selecting all the cells
for(let i=0; i<7; i++){
    const row = document.querySelectorAll(`.cell${i}`);
    origBoard.push(row);
}

//start game
function startGame(){
    document.querySelector(".endgame").style.diaplay = "none";
    for(let i=0; i<7; i++){
        for(let j=0; j<7; j++){
            origBoard[i][j].innerText = '';
            origBoard[i][j].addEventListener('click', turnClick, false);
        }
    }
}

//process after clicking a cell
function turnClick(square){
    turn(square.target.id, player1);
}

function turn(squareId, player){
    //console.log(squareId);
    document.getElementById(squareId).innerText = player;

    let gameWon = checkWin(origBoard, player, squareId);
    console.log(gameWon);
    // if(gameWon) gameOver(gameWon);

}